cilium_repo_url: https://helm.cilium.io
cilium_version: 1.16.1
cilium_namespace: kube-system
cilium_values:
  operator:
    replicas: 1
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6444
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  enableSourceIPVerification: false
  autoDirectNodeRoutes: true
  devices: "br-k3s"
  routingMode: "native"
  ipv4NativeRoutingCIDR: "192.168.0.0/24"
