- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - role: prerequisites
      tags: [prerequisites]
    - role: k3s
      tags: [k3s]
    # - automatic_upgrade  # Disabled for Proxmox/Debian compatibility

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - role: cilium
      tags: [cilium]
