all:
  vars:
    control_plane_endpoint: 192.168.0.200
    load_balancer_ip_pool:
      - 192.168.0.210/28
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.200, mac: 'not-needed-for-single-node', disk: nvme0n1, network_interface: br-k3s}
