k3s_version: v1.30.4+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_data_dir: /var/lib/rancher/k3s
k3s_kubeconfig_file: /etc/rancher/k3s/k3s.yaml
k3s_server_config:
  tls-san:
    - "{{ control_plane_endpoint }}"
  node-ip: "{{ control_plane_endpoint }}"
  node-external-ip: "{{ control_plane_endpoint }}"
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-helm-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  flannel-backend: none
  secrets-encryption: true
