argo-cd:
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.ostreros.xyz
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: homelab-tunnel.ostreros.xyz
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: true
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/xwalls/homelab
            revision: &revision master
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: master
